//
// Created by Neko Toxin on 2022/11/23.
//

#ifndef COMPILER_INTERMEDIATECODEGENERATOR_H
#define COMPILER_INTERMEDIATECODEGENERATOR_H


class IntermediateCodeGenerator {

};


#endif //COMPILER_INTERMEDIATECODEGENERATOR_H
